// Generated by CoffeeScript 1.3.1
(function() {
  var Backbone, _;

  if (typeof require !== "undefined" && require !== null) {
    Backbone = require("backbone");
    _ = require("underscore");
  } else {
    Backbone = window.Backbone;
    _ = window._;
  }

  Backbone.Decoratable = {
    decorate: function(n, fn) {
      var target, wrap;
      target = this[n];
      if (!_.isFunction(target)) {
        throw new Error("Can't decorate " + n + ", it's not a Function.");
      }
      if (target.fns == null) {
        wrap = function() {
          var args, finish, fns,
            _this = this;
          args = Array.prototype.slice.call(arguments);
          fns = _.clone(wrap.fns);
          finish = function() {
            var next;
            next = fns.shift();
            if (next) {
              return next.call(_this, finish);
            } else {
              return wrap.old.apply(_this, args);
            }
          };
          return finish();
        };
        _.extend(wrap, {
          fns: [],
          old: target
        });
        this[n] = target = wrap;
      }
      target.fns.push(fn);
      return this;
    }
  };

}).call(this);
