// Generated by CoffeeScript 1.3.1
(function() {
  var Backbone;

  if (typeof require !== "undefined" && require !== null) {
    Backbone = require("backbone");
  } else {
    Backbone = window.Backbone;
  }

  Backbone.Listenable = {
    listenTo: function(src, event, fn) {
      if (this.bindings == null) {
        this.bindings = [];
      }
      src.bind(event, fn, this);
      this.bindings.push({
        event: event,
        fn: fn,
        src: src
      });
      return this;
    },
    stopListening: function(src) {
      var b, _i, _len, _ref;
      if (this.bindings != null) {
        _ref = this.bindings;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          b = _ref[_i];
          if (!src || b.src === src) {
            b.src.off(b.event, b.fn);
          }
        }
        this.bindings = [];
      }
      return this;
    }
  };

}).call(this);
